### ISSUE TITLE
CDN?

### ISSUE THREAD

**Issue by jasonheecs** [filipelinhares/sanilize.css#13]
Hi, thanks for sharing this, this is really useful. Is this library on a CDN? It would be great if one can just insert a link tag to a CDN hosted version of this library.

**Comment by filipelinhares** [comment]
Thanks @jasonheecs :heart: 

I [added](https://github.com/filipelinhares/ress/commit/1a14ef68334914f0c4e78bb75fd0fce70b4b64ac) info about CDN [to the README](https://github.com/filipelinhares/ress#cdn).
