### ISSUE TITLE
Input content multiline

### ISSUE THREAD

**Issue by matteobad** [filipelinhares/sanilize.css#19]
Hi, I've noticed that the property `word-break: break-word` is behaving differently in different browsers. In particular, the content of an input tag, if too long, will break on multiple lines in Safari but not in Chrome.

Since the default value is `word-break: normal` I would suggest changing this. Let me know.
Thanks

**Comment by matteobad** [comment]
UPDATE: `break-word` is deprecated. So it should be changed
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by filipelinhares** [comment]
Thanks @matteobad.

I think its better to change to `word-break: normal;`.

**Comment by matteobad** [comment]
Should I open a PR?

**Comment by matteobad** [comment]
I've opened a PR!
