### ISSUE TITLE
border-style on iframe elements

### ISSUE THREAD

**Issue by matteobad** [filipelinhares/sanilize.css#27]
Hi @filipelinhares,

I noticed that `iframe` on chrome (didn't test other browsers) have the following:

```css
border-width: 2px;
border-style: inset;
border-color: initial;
border-image: initial;
```

I was thinking that maybe we could add a `border-style: none` to align default styling.
What do you think? Is this in the scope of this library?

Thank you in advance 😁

**Comment by filipelinhares** [comment]
Sorry the delay and thanks, @matteobad. This modification is in the last release https://github.com/filipelinhares/ress/commit/558430feb685b9b35116d8cbab73ff9dfd0c9b6a.
