### ISSUE TITLE
[disabled] rule is defined too soon

### ISSUE THREAD

**Issue by Mikk36** [filipelinhares/sanilize.css#30]
```
/* Replace pointer cursor in disabled elements */
[disabled] {
  cursor: default;
}
```
This rule is overridden by the button rule that sets the cursor to pointer.

Solution: define the rule later in the CSS.

**Comment by filipelinhares** [comment]
Thanks @Mikk36, this is fixed in the last release https://github.com/filipelinhares/ress/commit/a877ad0e20ca5065d30251cd9bde12b09f040dee.
