### ISSUE TITLE
Add eyeglass support

### ISSUE THREAD

**Issue by bpatram** [filipelinhares/sanilize.css#6]
This would allow others who use Eyeglass to easily import this package.
http://eyeglass.rocks/#writing-an-eyeglass-module-with-sass-files

Another package, [normalize-scss](https://github.com/JohnAlbin/normalize-scss) is a good example of how to set it up.

**Comment by filipelinhares** [comment]
Thanks for your suggestion.
ress will be kept in just CSS. If you want a `ress.sass` or something like that, feel free to make a fork :smile:

_I think eyeglass could import the [main](https://github.com/filipelinhares/ress/blob/master/package.json#L7) file and not require you to create a new sass folder, [etc, etc](https://github.com/JohnAlbin/normalize-scss/blob/master/package.json#L21-L25)._
