### ISSUE TITLE
Non minified version in dist

### ISSUE THREAD

**Issue by manchumahara** [filipelinhares/sanilize.css#9]
Can you please change your build system so that a non minified version is also stored in the dist folder. It helps sometimes.

**Comment by filipelinhares** [comment]
ress' [main file](https://github.com/filipelinhares/ress/blob/master/ress.css) is only CSS. If you need a minified version, you can use it.

The [build system](https://github.com/filipelinhares/ress/blob/master/package.json#L17) is just to minify the file and place it in the 'dist' directory
